// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;

namespace VacationsTracker.Android.Views
{
    public partial class LoginActivityViewHolder
    {
         private readonly Activity activity;

         private Button signInButton;
         private EditText passwordEditText;
         private EditText loginEditText;
         private LinearLayout errorMessageLayout;
         private TextView errorMessageTextView;

        public LoginActivityViewHolder( Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        
        public Button SignInButton =>
            signInButton ?? (signInButton = activity.FindViewById<Button>(Resource.Id.sign_in_button));

        
        public EditText PasswordEditText =>
            passwordEditText ?? (passwordEditText = activity.FindViewById<EditText>(Resource.Id.password_edit_text));

        
        public EditText LoginEditText =>
            loginEditText ?? (loginEditText = activity.FindViewById<EditText>(Resource.Id.login_edit_text));

        
        public LinearLayout ErrorMessageLayout =>
            errorMessageLayout ?? (errorMessageLayout = activity.FindViewById<LinearLayout>(Resource.Id.error_message_layout));

        
        public TextView ErrorMessageTextView =>
            errorMessageTextView ?? (errorMessageTextView = activity.FindViewById<TextView>(Resource.Id.error_message_text_view));
    }
}
// ReSharper restore All
