// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;

namespace VacationsTracker.Droid.Views
{
    public partial class LoginActivityViewHolder
    {
         private readonly Activity activity;

         private LinearLayout errorMessageLayout;
         private TextView errorMessageTextView;
         private EditText loginEditText;
         private EditText passwordEditText;
         private Button signInButton;

        public LoginActivityViewHolder( Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        
        public LinearLayout ErrorMessageLayout =>
            errorMessageLayout ?? (errorMessageLayout = activity.FindViewById<LinearLayout>(Resource.Id.error_message_layout));

        
        public TextView ErrorMessageTextView =>
            errorMessageTextView ?? (errorMessageTextView = activity.FindViewById<TextView>(Resource.Id.error_message_text_view));

        
        public EditText LoginEditText =>
            loginEditText ?? (loginEditText = activity.FindViewById<EditText>(Resource.Id.login_edit_text));

        
        public EditText PasswordEditText =>
            passwordEditText ?? (passwordEditText = activity.FindViewById<EditText>(Resource.Id.password_edit_text));

        
        public Button SignInButton =>
            signInButton ?? (signInButton = activity.FindViewById<Button>(Resource.Id.sign_in_button));
    }

    public partial class MainListActivityViewHolder
    {
         private readonly Activity activity;

         private Android.Support.V4.Widget.DrawerLayout drawerLayout;
         private Android.Support.V4.Widget.SwipeRefreshLayout refresher;
         private Android.Support.V7.Widget.RecyclerView recyclerView;
         private Android.Support.Design.Widget.FloatingActionButton fab;
         private Android.Support.Design.Widget.NavigationView navigationView;

        public MainListActivityViewHolder( Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        
        public Android.Support.V4.Widget.DrawerLayout DrawerLayout =>
            drawerLayout ?? (drawerLayout = activity.FindViewById<Android.Support.V4.Widget.DrawerLayout>(Resource.Id.drawer_layout));

        
        public Android.Support.V4.Widget.SwipeRefreshLayout Refresher =>
            refresher ?? (refresher = activity.FindViewById<Android.Support.V4.Widget.SwipeRefreshLayout>(Resource.Id.refresher));

        
        public Android.Support.V7.Widget.RecyclerView RecyclerView =>
            recyclerView ?? (recyclerView = activity.FindViewById<Android.Support.V7.Widget.RecyclerView>(Resource.Id.recycler_view));

        
        public Android.Support.Design.Widget.FloatingActionButton Fab =>
            fab ?? (fab = activity.FindViewById<Android.Support.Design.Widget.FloatingActionButton>(Resource.Id.fab));

        
        public Android.Support.Design.Widget.NavigationView NavigationView =>
            navigationView ?? (navigationView = activity.FindViewById<Android.Support.Design.Widget.NavigationView>(Resource.Id.navigation_view));
    }

    public partial class VacationCellViewHolder
    {
         private ImageView vacationImage;
         private TextView vacationDuration;
         private TextView vacationType;
         private TextView vacationStatus;
         private View separatorView;



        
        public ImageView VacationImage =>
            vacationImage ?? (vacationImage = ItemView.FindViewById<ImageView>(Resource.Id.vacation_image));

        
        public TextView VacationDuration =>
            vacationDuration ?? (vacationDuration = ItemView.FindViewById<TextView>(Resource.Id.vacation_duration));

        
        public TextView VacationType =>
            vacationType ?? (vacationType = ItemView.FindViewById<TextView>(Resource.Id.vacation_type));

        
        public TextView VacationStatus =>
            vacationStatus ?? (vacationStatus = ItemView.FindViewById<TextView>(Resource.Id.vacation_status));

        
        public View SeparatorView =>
            separatorView ?? (separatorView = ItemView.FindViewById<View>(Resource.Id.separator_view));
    }

    /*
    "LayoutDefinitionOptions" are not specified for "navigation_header" layout file therefore view holder can't be generated for it.
    public partial class HeaderNavigationViewHolder
    {
    }
    */

    /*
    "LayoutDefinitionOptions" are not specified for "navigation_menu" layout file therefore view holder can't be generated for it.
    public partial class MenuNavigationViewHolder
    {
    }
    */

    /*
    "LayoutDefinitionOptions" are not specified for "toolbar" layout file therefore view holder can't be generated for it.
    public partial class ToolbarViewHolder
    {
    }
    */

}
// ReSharper restore All
